### ISSUE TITLE
getting errors

### ISSUE THREAD

**Issue by sveco86** [smar000/evohome-Listener#24]
I am getting errors in evohome Listener/Sender Gateway version 2.0.1:

2020-11-06 15:24:13 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 074  I --- 04:001827 --:------ 04:001827 30C9 003 0009A        6', port: 1]
Traceback (most recent call last):
  File "evogateway.py", line 718, in process_received_message
    COMMANDS[msg.command_code](msg)
  File "evogateway.py", line 876, in zone_temperature
    mqtt_publish("{}/{}".format(zones[zone_id], msg.source_name), "temperature",temperature)
KeyError: -1

2020-11-06 15:24:17 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 074  I --- 04:001821 --:------ 04:001821 30C9 003 0009C        5', port: 1]
Traceback (most recent call last):
  File "evogateway.py", line 718, in process_received_message
    COMMANDS[msg.command_code](msg)
  File "evogateway.py", line 876, in zone_temperature
    mqtt_publish("{}/{}".format(zones[zone_id], msg.source_name), "temperature",temperature)
KeyError: -1

2020-11-06 15:24:52 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 071  I --- 04:001145 --:------ 04:001145 30C9 003 00099        3', port: 1]
Traceback (most recent call last):
  File "evogateway.py", line 718, in process_received_message
    COMMANDS[msg.command_code](msg)
  File "evogateway.py", line 876, in zone_temperature
    mqtt_publish("{}/{}".format(zones[zone_id], msg.source_name), "temperature",temperature)
KeyError: -1

2020-11-06 15:25:36 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 082  I --- 04:001825 --:------ 04:001825 30C9 003 000935', port: 1]
Traceback (most recent call last):
  File "evogateway.py", line 718, in process_received_message
    COMMANDS[msg.command_code](msg)
  File "evogateway.py", line 876, in zone_temperature
    mqtt_publish("{}/{}".format(zones[zone_id], msg.source_name), "temperature",temperature)
KeyError: -1

2020-11-06 15:26:33 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 083  I --- 04:002051 --:------ 04:002051 30C9 003 0009C0', port: 1]
Traceback (most recent call last):
  File "evogateway.py", line 718, in process_received_message
    COMMANDS[msg.command_code](msg)
  File "evogateway.py", line 876, in zone_temperature
    mqtt_publish("{}/{}".format(zones[zone_id], msg.source_name), "temperature",temperature)
KeyError: -1

2020-11-06 15:27:10 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 062  I --- 01:214357 --:------ 01:214357 30C9 021 00091801091B0309350409C50509A60609C00708FA', port: 1]
Traceback (most recent call last):
  File "evogateway.py", line 718, in process_received_message
    COMMANDS[msg.command_code](msg)
  File "evogateway.py", line 876, in zone_temperature
    mqtt_publish("{}/{}".format(zones[zone_id], msg.source_name), "temperature",temperature)
KeyError: -1

2020-11-06 15:27:18 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 080  I --- 04:001099 --:------ 04:001099 30C9 003 0008C3', port: 1]
Traceback (most recent call last):
  File "evogateway.py", line 718, in process_received_message
    COMMANDS[msg.command_code](msg)
  File "evogateway.py", line 876, in zone_temperature
    mqtt_publish("{}/{}".format(zones[zone_id], msg.source_name), "temperature",temperature)
KeyError: -1

2020-11-06 15:27:39 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 074  I --- 04:001819 --:------ 04:001819 30C9 003 000931', port: 1]
Traceback (most recent call last):
  File "evogateway.py", line 718, in process_received_message
    COMMANDS[msg.command_code](msg)
  File "evogateway.py", line 876, in zone_temperature
    mqtt_publish("{}/{}".format(zones[zone_id], msg.source_name), "temperature",temperature)
KeyError: -1

**Comment by smar000** [comment]
I'm guessing that your zones may not have been correctly defined. Have you set the zones for each device in your devices config file?

**Comment by sveco86** [comment]
Thank you for your answer.
All related errors are related to device "01:214357" which I do not recognize. I really do not know what is this device because all my TRV, heating relay (13:054620) and EvoGateway (18:056026).

Errors:
```
2020-11-07 16:39:39 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 073  I --- 01:214357 --:------ 01:214357 30C9 021 0008EF0107B603098404082F0509300609D307090A', port: 1]
2020-11-07 16:55:47 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 069  I --- 01:214357 --:------ 01:214357 30C9 021 00099B0107A30309A60408340509300609B30708F7', port: 1]
2020-11-07 17:19:59 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 073  I --- 01:214357 --:------ 01:214357 30C9 021 00099C0108110309B90408710509300609B30708D2', port: 1]
2020-11-07 17:32:05 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 071  I --- 01:214357 --:------ 01:214357 30C9 021 00095E01082603098D04087105091E0609B30708BE', port: 1]
2020-11-07 17:36:07 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 070  I --- 01:214357 --:------ 01:214357 30C9 021 00094901082603098D04087105091E0609B30708BE', port: 1]
2020-11-07 17:48:13 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 072  I --- 01:214357 --:------ 01:214357 30C9 021 00090D01082603096604087105090B0609990708AC', port: 1]
2020-11-07 17:52:15 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 070  I --- 01:214357 --:------ 01:214357 30C9 021 0008F901082603094E0408710508F70609990708AC', port: 1]
2020-11-07 18:00:19 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 071  I --- 01:214357 --:------ 01:214357 30C9 021 0008E40108120309380408710508F70609840708AC', port: 1]
2020-11-07 18:04:21 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 070  I --- 01:214357 --:------ 01:214357 30C9 021 0008E40108120309380408710508F70609840708AC', port: 1]
2020-11-07 18:08:23 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 070  I --- 01:214357 --:------ 01:214357 30C9 021 0008E40107FE03092204087105092B0609840708AC', port: 1]
2020-11-07 18:12:25 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 071  I --- 01:214357 --:------ 01:214357 30C9 021 0008E40107FE03091004085E05095C0609840708AC', port: 1]
2020-11-07 18:20:29 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 071  I --- 01:214357 --:------ 01:214357 30C9 021 0009120107EC0308FA04085E0509D006096F0708AC', port: 1]
2020-11-07 18:24:31 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 070  I --- 01:214357 --:------ 01:214357 30C9 021 00092A0107EC0308FA04085E050A0506095C0708AC', port: 1]
2020-11-07 18:28:33 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 074  I --- 01:214357 --:------ 01:214357 30C9 021 00093D0107EC0308FA04085E050A3306095C0708AC', port: 1]
2020-11-07 18:32:35 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 070  I --- 01:214357 --:------ 01:214357 30C9 021 00094F0107D90308E804085E050A4506095C0708AC', port: 1]
2020-11-07 18:36:37 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 069  I --- 01:214357 --:------ 01:214357 30C9 021 0009630107D90308E804084B050A6F06095C0708AC', port: 1]
2020-11-07 18:40:39 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 068  I --- 01:214357 --:------ 01:214357 30C9 021 0009630107D90308D404084B050A6F06095C0708AC', port: 1]
2020-11-07 18:44:41 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 069  I --- 01:214357 --:------ 01:214357 30C9 021 0009630107D90308C104084B050A850609740708AC', port: 1]
2020-11-07 18:48:43 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 069  I --- 01:214357 --:------ 01:214357 30C9 021 00094C0107D90308C104084B050A8506098C0708B0', port: 1]
2020-11-07 16:27:33 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 071  I --- 01:214357 --:------ 01:214357 30C9 021 0008970107B603098404082F0509440609E707091F', port: 1]
2020-11-07 16:31:35 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 072  I --- 01:214357 --:------ 01:214357 30C9 021 0008970107B603098404082F0509440609E707091F', port: 1]
2020-11-07 16:05:17 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 088  I --- 04:001099 --:------ 04:001099 30C9 003 00088E', port: 1]
2020-11-07 16:07:23 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 072  I --- 01:214357 --:------ 01:214357 30C9 021 0008C30107B603098404082F05097E060A0E07095D', port: 1]
2020-11-07 16:11:25 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 082  I --- 01:214357 --:------ 01:214357 30C9 021 0008AD0107B603098404082F05096A060A0E07095D', port: 1]
2020-11-07 16:12:18 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 086  I --- 04:001099 --:------ 04:001099 30C9 003 000878', port: 1]
2020-11-07 16:15:27 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 074  I --- 01:214357 --:------ 01:214357 30C9 021 0008970107B603098404082F05096A0609FB070947', port: 1]
2020-11-07 16:19:29 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 073  I --- 01:214357 --:------ 01:214357 30C9 021 0008970107B603098404082F05096A0609FB070933', port: 1]
2020-11-07 16:23:31 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 072  I --- 01:214357 --:------ 01:214357 30C9 021 0008970107B603098404082F0509570609FB070933', port: 1]
```


Here is my devices_new.json
```
{
    "01:214357": {
        "name": "01:214357",
        "zoneId": -1,
        "zoneMaster": false
    },
    "04:001097": {
        "name": "ObyvackaP",
        "zoneId": 1,
        "zoneMaster": true
    },
    "04:001099": {
        "name": "ObyvackaL",
        "zoneId": 1,
        "zoneMaster": false
    },
    "04:001145": {
        "name": "Kuchyna",
        "zoneId": 3,
        "zoneMaster": true
    },
    "04:001819": {
        "name": "Hostovska",
        "zoneId": 2,
        "zoneMaster": true
    },
    "04:001821": {
        "name": "Izba Peto",
        "zoneId": 5,
        "zoneMaster": true
    },
    "04:001825": {
        "name": "Spalna",
        "zoneId": 4,
        "zoneMaster": true
    },
    "04:001827": {
        "name": "Kupelna",
        "zoneId": 6,
        "zoneMaster": true
    },
    "04:001831": {
        "name": "Umyvarka",
        "zoneId": 8,
        "zoneMaster": true
    },
    "04:002051": {
        "name": "Izba Marek",
        "zoneId": 7,
        "zoneMaster": true
    },
    "04:002055": {
        "name": "Izba prizemie",
        "zoneId": 3,
        "zoneMaster": false
    },
    "13:054620": {
        "name": "Spinac kotla",
        "zoneId": 0,
        "zoneMaster": false
    },
    "18:056026": {
        "name": "EvoGateway",
        "zoneId": 240,
        "zoneMaster": true
    }

```

Here is my devices.json:
```
{
    "04:001831": { "name" : "Umyvarka", "zoneId" : 8, "zoneMaster" : true},
    "04:002055": { "name" : "Izba prizemie", "zoneId" : 3, "zoneMaster" : false},
    "04:001145": { "name" : "Kuchyna", "zoneId" : 3, "zoneMaster" : true},
    "04:001097": { "name" : "ObyvackaP", "zoneId" : 1, "zoneMaster" : true},
    "04:001099": { "name" : "ObyvackaL", "zoneId" : 1, "zoneMaster" : false},
    "04:001819": { "name" : "Hostovska", "zoneId" : 2, "zoneMaster" : true},
    "04:001821": { "name" : "Izba Peto", "zoneId" : 5, "zoneMaster" : true},
    "04:001827": { "name" : "Kupelna", "zoneId" : 6, "zoneMaster" : true},
    "04:002051": { "name" : "Izba Marek", "zoneId" : 7, "zoneMaster" : true},
    "13:054620": { "name" : "Spinac kotla", "zoneId" : 0, "zoneMaster" : false},
    "04:001825": { "name" : "Spalna", "zoneId" : 4, "zoneMaster" : true}
}
```

**Comment by sveco86** [comment]
cat events.log* | grep "214357"

```

2020-11-07 16:38:42 |     | NEW DEVICE FOUND    | 01:214357
2020-11-07 16:39:39 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 073  I --- 01:214357 --:------ 01:214357 30C9 021 0008EF0107B603098404082F0509300609D307090A', port: 1]
2020-11-07 16:49:54 |1/071| ZONE_NAME           | RP| CTL 01:214357          -> TRV Izba Marek         | Payload: 0600497A6261204D6172656B00000000000000000000 Payload length: 22
2020-11-07 16:50:53 |1/069| ZONE_NAME           | RP| CTL 01:214357          -> TRV Izba Peto          | Payload: 0400497A6261205065746F0000000000000000000000 Payload length: 22
2020-11-07 16:54:46 |1/071| ZONE_NAME           | RP| CTL 01:214357          -> TRV Hostovska          | Payload: 0100486F73746F76736B610000000000000000000000 Payload length: 22
2020-11-07 16:55:47 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 069  I --- 01:214357 --:------ 01:214357 30C9 021 00099B0107A30309A60408340509300609B30708F7', port: 1]
2020-11-07 17:19:59 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 073  I --- 01:214357 --:------ 01:214357 30C9 021 00099C0108110309B90408710509300609B30708D2', port: 1]
2020-11-07 17:32:05 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 071  I --- 01:214357 --:------ 01:214357 30C9 021 00095E01082603098D04087105091E0609B30708BE', port: 1]
2020-11-07 17:36:07 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 070  I --- 01:214357 --:------ 01:214357 30C9 021 00094901082603098D04087105091E0609B30708BE', port: 1]
2020-11-07 17:37:54 |1/070| ACTUATOR_STATE      | RQ| CTL 01:214357          -> BDR Spinac kotla       | Request actuator state update
2020-11-07 17:37:56 |1/071| ACTUATOR_STATE      | RQ| CTL 01:214357          -> BDR Spinac kotla       | Request actuator state update
2020-11-07 17:37:58 |1/071| ACTUATOR_STATE      | RQ| CTL 01:214357          -> BDR Spinac kotla       | Request actuator state update
2020-11-07 17:48:13 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 072  I --- 01:214357 --:------ 01:214357 30C9 021 00090D01082603096604087105090B0609990708AC', port: 1]
2020-11-07 17:52:15 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 070  I --- 01:214357 --:------ 01:214357 30C9 021 0008F901082603094E0408710508F70609990708AC', port: 1]
2020-11-07 18:00:19 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 071  I --- 01:214357 --:------ 01:214357 30C9 021 0008E40108120309380408710508F70609840708AC', port: 1]
2020-11-07 18:04:21 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 070  I --- 01:214357 --:------ 01:214357 30C9 021 0008E40108120309380408710508F70609840708AC', port: 1]
2020-11-07 18:05:13 |1/068| ZONE_NAME           | RP| CTL 01:214357          -> TRV Spalna             | Payload: 03005370E16C6E610000000000000000000000000000 Payload length: 22
2020-11-07 18:08:23 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 070  I --- 01:214357 --:------ 01:214357 30C9 021 0008E40107FE03092204087105092B0609840708AC', port: 1]
2020-11-07 18:12:25 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 071  I --- 01:214357 --:------ 01:214357 30C9 021 0008E40107FE03091004085E05095C0609840708AC', port: 1]
2020-11-07 18:20:29 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 071  I --- 01:214357 --:------ 01:214357 30C9 021 0009120107EC0308FA04085E0509D006096F0708AC', port: 1]
2020-11-07 18:24:31 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 070  I --- 01:214357 --:------ 01:214357 30C9 021 00092A0107EC0308FA04085E050A0506095C0708AC', port: 1]
2020-11-07 18:28:33 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 074  I --- 01:214357 --:------ 01:214357 30C9 021 00093D0107EC0308FA04085E050A3306095C0708AC', port: 1]
2020-11-07 18:32:35 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 070  I --- 01:214357 --:------ 01:214357 30C9 021 00094F0107D90308E804085E050A4506095C0708AC', port: 1]
2020-11-07 18:36:37 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 069  I --- 01:214357 --:------ 01:214357 30C9 021 0009630107D90308E804084B050A6F06095C0708AC', port: 1]
2020-11-07 18:37:54 |1/071| ACTUATOR_STATE      | RQ| CTL 01:214357          -> BDR Spinac kotla       | Request actuator state update
2020-11-07 18:40:39 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 068  I --- 01:214357 --:------ 01:214357 30C9 021 0009630107D90308D404084B050A6F06095C0708AC', port: 1]
2020-11-07 18:44:41 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 069  I --- 01:214357 --:------ 01:214357 30C9 021 0009630107D90308C104084B050A850609740708AC', port: 1]
2020-11-07 18:48:43 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 069  I --- 01:214357 --:------ 01:214357 30C9 021 00094C0107D90308C104084B050A8506098C0708B0', port: 1]
2020-11-07 18:49:12 |1/070| ZONE_NAME           | RP| CTL 01:214357          -> TRV Kupelna            | Payload: 05004BFA70656C6E6100000000000000000000000000 Payload length: 22
2020-11-07 18:52:45 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 073  I --- 01:214357 --:------ 01:214357 30C9 021 0009380107D90308C104084B050A920609B70708B0', port: 1]
2020-11-07 18:56:47 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 070  I --- 01:214357 --:------ 01:214357 30C9 021 0009380107C70308C104084B050A920609D00708B0', port: 1]
2020-11-07 19:00:49 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 069  I --- 01:214357 --:------ 01:214357 30C9 021 0009260107C70308AE040839050A920609E80708B0', port: 1]
2020-11-07 16:26:34 |1/077| SETPOINT            | I | TRV Umyvarka           -> 01:214357              | 22.00°C @ Umyvarka                [Zone 8  ]
2020-11-07 16:27:33 |     | NEW DEVICE FOUND    | 01:214357
2020-11-07 16:27:33 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 071  I --- 01:214357 --:------ 01:214357 30C9 021 0008970107B603098404082F0509440609E707091F', port: 1]
2020-11-07 16:31:35 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 072  I --- 01:214357 --:------ 01:214357 30C9 021 0008970107B603098404082F0509440609E707091F', port: 1]
2020-11-07 16:37:57 |1/071| ACTUATOR_STATE      | RQ| CTL 01:214357          -> BDR Spinac kotla       | Request actuator state update
2020-11-07 16:02:49 |1/074| ZONE_HEAT_DEMAND    | I | TRV Izba prizemie      -> 01:214357              |   51.0% @ Kuchyna                 [Zone 3  ]
2020-11-07 16:03:21 |     | NEW DEVICE FOUND    | 01:214357
2020-11-07 16:07:23 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 072  I --- 01:214357 --:------ 01:214357 30C9 021 0008C30107B603098404082F05097E060A0E07095D', port: 1]
2020-11-07 16:11:25 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 082  I --- 01:214357 --:------ 01:214357 30C9 021 0008AD0107B603098404082F05096A060A0E07095D', port: 1]
2020-11-07 16:15:27 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 074  I --- 01:214357 --:------ 01:214357 30C9 021 0008970107B603098404082F05096A0609FB070947', port: 1]
2020-11-07 16:19:29 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 073  I --- 01:214357 --:------ 01:214357 30C9 021 0008970107B603098404082F05096A0609FB070933', port: 1]
2020-11-07 16:23:31 |     | ERROR               | '-1' on line 718 [Command ZONE_TEMPERATURE, data: '--- 072  I --- 01:214357 --:------ 01:214357 30C9 021 0008970107B603098404082F0509570609FB070933', port: 1]
```

**Comment by smar000** [comment]
Device type `01`  is for your evohome controller (with full ID `01:214357`). Add this to your `devices.json` file and change the zone for this from `-1` to whatever the zone number is for where you have the controller located.

**Comment by sveco86** [comment]
now it looks ok, thank you!!
