### ISSUE TITLE
AttributeError: 'Gateway' object has no attribute 'evo'

### ISSUE THREAD

**Issue by ajin** [smar000/evohome-Listener#50]
An `AttributeError: 'Gateway' object has no attribute 'evo'` occurs after closing the application and fails to generate the `devices.json` and `ramses_rf_schema.json`. In the previous release it was working fine. 

Here is the full trace: 

```
2023-01-14 21:22:35 |050| CTL Controller        -> HGI evoGateway        |RP| tpi_params      | cycle_rate: 6, domain_id: FC, min_off_time: 0.0, min_on_time: 5.0, proportional_band_width: null
2023-01-14 21:22:35 |000| HGI evoGateway        -> CTL Controller        |RQ| system_fault    | REQUEST: system_fault
^CMsgTransport.pkt_dispatcher(): connection_lost(None)
Traceback (most recent call last):
  File "/home/ajin/Documents/evoGateway/evogateway.py", line 1264, in <module>
    print_ramsesrf_gwy_schema(GWY)
  File "/home/ajin/Documents/evoGateway/evogateway.py", line 483, in print_ramsesrf_gwy_schema
    if gwy.evo is None:
AttributeError: 'Gateway' object has no attribute 'evo'
```

**Comment by smar000** [comment]
Unfortunately it looks as if I had missed a couple of changes related to the newer ramses_rf. I will get an update out tomorrow, but in the meantime you could use the `client.py` script in the ramses repository to get an updated schema.

**Comment by smar000** [comment]
Schema saving should be working on the build pushed a few minutes ago.

**Comment by ajin** [comment]
I can confirm that 369c1dd8978a8f4b42757f6b4860b289770a0647 solved the issue. There was also an issue related to schema generation which is also got resolved with the same commit. Thanks!
